"""Get things up to date

Revision ID: e2ac7f98af16
Revises: 
Create Date: 2021-06-19 22:55:31.677428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2ac7f98af16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Old stuff
    op.create_index(op.f('ix_badges_server_id'), 'badges', ['server_id'], unique=False)
    op.create_index(op.f('ix_badges_name'), 'badges', ['name'], unique=False)
    op.alter_column('badges', 'icon', type_=sa.String(128, collation="utf8mb4_unicode_ci"))
    op.create_index(op.f('ix_badges_icon'), 'badges', ['icon'], unique=False)

    #migrating botops
    op.rename_table('botopts', 'bot_options')

    #migrating serveropts
    op.rename_table('serveropts', 'server_options')
    op.create_index(op.f('ix_server_options_server_id'), 'server_options', ['server_id'], unique=False)

    #migrating badgewinners
    op.rename_table('badgewinners', 'badge_winners')
    op.create_index(op.f('ix_badge_winners_discord_id'), 'badge_winners', ['discord_id'], unique=False)
    op.create_index(op.f('ix_badge_winners_server_id'), 'badge_winners', ['server_id'], unique=False)
    
    print("WARNING: tags table is not migrated automatically to prevent data loss.")
    """
    op.drop_column('tags', 'id')
    op.create_primary_key(
                "pk_tags", "tags",
                ["server_id", "name"]
            )
    """

    # New stuff
    op.create_table('backgrounds',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=150, collation='utf8mb4_unicode_ci'), nullable=False),
        sa.Column('description', sa.Text(collation='utf8mb4_unicode_ci'), nullable=True),
        sa.Column('image_url', sa.Text(length=500, collation='utf8mb4_unicode_ci'), nullable=False),
        sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
        sa.Column('usable_by_default', sa.Boolean(), nullable=False),
        sa.Column('hidden', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_backgrounds')),
        sa.UniqueConstraint('server_id', 'name', name=op.f('uq_backgrounds_server_id'))
    )
    op.create_index(op.f('ix_backgrounds_name'), 'backgrounds', ['name'], unique=False)
    op.create_index(op.f('ix_backgrounds_server_id'), 'backgrounds', ['server_id'], unique=False)

    op.create_table('background_winners',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.BigInteger(), nullable=False),
        sa.Column('discord_id', sa.BigInteger(), nullable=False),
        sa.Column('background_id', sa.Integer(), nullable=False),
        sa.Column('awarded', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['background_id'], ['backgrounds.id'], name=op.f('fk_background_winners_background_id_backgrounds'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_background_winners')),
        sa.UniqueConstraint('discord_id', 'background_id', name=op.f('uq_background_winners_discord_id'))
    )
    op.create_index(op.f('ix_background_winners_discord_id'), 'background_winners', ['discord_id'], unique=False)
    op.create_index(op.f('ix_background_winners_server_id'), 'background_winners', ['server_id'], unique=False)

    op.create_table('profile_preferences',
        sa.Column('server_id', sa.BigInteger(), nullable=False),
        sa.Column('discord_id', sa.BigInteger(), nullable=False),
        sa.Column('spotlighted_award_id', sa.Integer(), nullable=True),
        sa.Column('background_award_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['background_award_id'], ['background_winners.id'], name=op.f('fk_profile_preferences_background_award_id_background_winners'), ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['spotlighted_award_id'], ['badge_winners.id'], name=op.f('fk_profile_preferences_spotlighted_award_id_badge_winners'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('server_id', 'discord_id', name=op.f('pk_profile_preferences'))
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('tags', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))

    op.drop_index(op.f('ix_badges_server_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_name'), table_name='badges')
    op.drop_index(op.f('ix_badges_icon'), table_name='badges')

    op.drop_index(op.f('ix_badge_winners_server_id'), table_name='badge_winners')
    op.drop_index(op.f('ix_badge_winners_discord_id'), table_name='badge_winners')

    op.drop_index(op.f('ix_server_options_server_id'), table_name='server_options')

    op.rename_table('server_options', 'serveropts')
    op.rename_table('badge_winners', 'badgewinners')
    op.rename_table('bot_options', 'botopts')

    op.drop_table('profile_preferences')
    op.drop_table('background_winners')
    op.drop_table('backgrounds')
    # ### end Alembic commands ###
